language: java
env:
  - DB=mysql
jdk:
  - oraclejdk8
script:
    mvn --errors --strict-checksums --fail-fast -Dfile.encoding=UTF-8 clean -P travis-ci-env initialize package
before_script:
  - mysql -e 'create database jsf_test'
